security:
    providers:
        admin:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: "^%admin_path%"
            anonymous: true
            provider: admin
            form_login:
                login_path: "%admin_path%/login"
                check_path: "%admin_path%/login_check"
                default_target_path: "%admin_path%"
                remember_me: true
            logout:
                path: "%admin_path%/logout"
                target: "%admin_path%/login"
            remember_me:
                key: %secret%

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: "^%admin_path%/login", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%admin_path%/login_check", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%admin_path%", roles: [ROLE_SONATA_ADMIN] }

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha512
            encode_as_base64: true
            iterations: 2000
        Alpixel\Bundle\AlpixelUserBundle\Entity\Admin:
            algorithm: sha512
            encode_as_base64: true
            iterations: 2000

alpixel_user:
    firewall_templates:
        admin:
            login_template: 'UserBundle:admin:pages/back_login.html.twig'

