security:
    providers:
        admin:
            entity:
                class: Alpixel\Bundle\UserBundle\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: "^%admin_path%"
            anonymous: true
            provider: admin
            form_login:
                login_path: "%admin_path%/login"
                check_path: "%admin_path%/login_check"
                default_target_path: "%admin_path%"
                remember_me: true
            logout:
                path: "%admin_path%/logout"
                target: "%admin_path%/login"
            remember_me:
                key: %secret%

    role_hierarchy:
       ROLE_USER: ROLE_USER
       ROLE_ADMIN: [ROLE_SONATA_ADMIN, ROLE_ADMIN]
       ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: "^%admin_path%/login", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%admin_path%/login_check", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%admin_path%", roles: [ROLE_SONATA_ADMIN] }

    encoders:
       Alpixel\Bundle\UserBundle\Entity\Admin:
            algorithm: pbkdf2
            hash_algorithm: sha512
            encode_as_base64: true
            iterations: 5000
            iterations: 1000
            key_length: 40

alpixel_user:
    default_login_background_image: '../../bundles/alpixeluser/img/background.jpg'
    default_login_background_color: '#ff656c'
    firewall_templates:
        admin:
            login_path: "%admin_path%/login"
            login_check: "%admin_path%/login_check"
            login_template: 'AlpixelUserBundle:admin:page/login.html.twig'

