services:
    user.admin.admin:
        class: Alpixel\Bundle\UserBundle\Admin\AdminAdmin
        arguments: [~, Alpixel\Bundle\UserBundle\Entity\Admin, UserBundle:AdminAdmin]
        calls:
            - [ setUserManager, [ '@fos_user.user_manager' ] ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Utilisateurs', label: 'Administrateurs'}
