language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.8.*


matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.3.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*

before_install:
    - travis_retry composer self-update

install:
  - composer update $COMPOSER_FLAGS --prefer-source --no-interaction

script: phpunit --coverage-text
