services:
    access:
        class: Alpixel\Bundle\UserBundle\Services\AccessManager
        arguments:    [@security.context]

    authentication_handler:
        class: Alpixel\Bundle\UserBundle\Handler\AuthenticationHandler
        arguments:    [@router]

    user.provider.oauth:
        class: Alpixel\Bundle\UserBundle\Provider\OAuthUserProvider
        arguments:    ['@fos_user.user_manager',  { facebook: facebookId, twitter: twitterId }, @event_dispatcher]
        calls:
            - [setRequest, [@request_stack]]

    user.admin.admin:
        class: Alpixel\Bundle\UserBundle\Admin\AdminAdmin
        arguments: [~, Alpixel\Bundle\UserBundle\Entity\Admin, UserBundle:AdminAdmin]
        calls:
            - [ setUserManager, [ @fos_user.user_manager ] ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Utilisateurs', label: 'Administrateurs'}
